version: '3.5'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
    school:
      build:
        context: .
      image: school
      volumes:
        - ./pv/seq:/mnt/data
      ports:
        - 8081:80
      networks:
        - frontend
        - backend
      depends_on:
        - mysql
        - redis

    queue:
      image: school
      depends_on: school
      command: php /app/artisan horizon
      volumes:
        - ./pv/seq:/mnt/data
        - ./pv/db:/mnt/db
      ports:
        - 8082:80
      networks:
        - backend
      depends_on:
        - mysql
        - redis

    redis:
      build: ./redis
      volumes:
        - ./pv/redis:/data
      ports:
        - 16379:6379
      networks:
        - backend

    mysql:
      build:
        context: ./mysql
      environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        - TZ="Asia/Shanghai"
      volumes:
        - ./pv/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - 13306:3306
      networks:
        - backend
