# https://github.com/renoki-co/laravel-docker-base
FROM quay.io/renokico/laravel-base:octane-1.1.0-4.6-php8.0-alpine

# install pecl extension
RUN pecl install mongodb && docker-php-ext-enable mongodb && rm -rf /tmp/pear

COPY --chown=www-data:www-data . /var/www/html

WORKDIR /var/www/html

ENTRYPOINT ["php", "-d", "variables_order=EGPCS", "artisan", "octane:start", "--server=swoole", "--host=0.0.0.0", "--port=80"]

EXPOSE 80
